"""Replay retained inputs twice, with explicit independently pinned Crown census."""

# ruff: noqa: INP001
from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from pathlib import Path

from archive_govt_nz.domains.health_appropriations.rebuild_eight import (
    SOURCE_SHA256,
    execute_eight,
    plan_eight,
    verify_eight,
)


def digest(path: Path) -> str:
    """Hash actual retained or freshly generated bytes."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    """Print only bounded fixity/results; keep original and output bytes outside Git."""
    archive, output, census = map(Path, sys.argv[1:4])
    donor = archive / "manifests/donor-4668e6c.json"
    store = archive / "bronze-cas"
    donor_pin, census_pin = digest(donor), digest(census)
    plan = plan_eight(
        donor,
        store,
        donor_pin,
        "2026-08-30T08:58:00+00:00",
        SOURCE_SHA256,
        crown_receipt=census,
        crown_receipt_sha256=census_pin,
    )
    cli = subprocess.run(  # noqa: S603 -- fixed module command with explicit local paths.
        [
            sys.executable,
            "-m",
            "archive_govt_nz",
            "health-appropriations-rebuild",
            "--donor-manifest",
            str(donor),
            "--store-root",
            str(store),
            "--manifest-sha256",
            donor_pin,
            "--observed-at",
            "2026-08-30T08:58:00+00:00",
            "--eight-stage",
            "--crown-source-sha256",
            SOURCE_SHA256,
            "--crown-receipt",
            str(census),
            "--crown-receipt-sha256",
            census_pin,
            "--output-dir",
            str(output / "dry-run"),
        ],
        capture_output=True,
        text=True,
        check=True,
        timeout=60,
    )
    if json.loads(cli.stdout)["plan"] != plan or (output / "dry-run").exists():
        message = "cli_plan_mismatch"
        raise ValueError(message)
    inventories = []
    for label in ("first", "second"):
        root = output / label
        receipt = execute_eight(plan, store, root)
        if verify_eight(root, store, digest(root / "MANIFEST.json")) != receipt:
            message = "replay_verification_mismatch"
            raise ValueError(message)
        inventories.append(
            {
                path.relative_to(root).as_posix(): digest(path)
                for path in sorted(root.rglob("*"))
                if path.is_file()
            }
        )
    if (
        inventories[0] != inventories[1]
        or digest(census) != census_pin
        or digest(donor) != donor_pin
    ):
        message = "replay_fixity_mismatch"
        raise ValueError(message)
    print(  # noqa: T201 -- bounded machine-readable replay evidence.
        json.dumps(
            {
                "mode": "local_retained_source_replay",
                "output_root": str(output),
                "crown_receipt": str(census),
                "crown_receipt_sha256": census_pin,
                "donor_manifest_sha256": donor_pin,
                "crown_object_sha256": SOURCE_SHA256,
                "cli_default_no_write": True,
                "builds_identical": True,
                "counts": {row["stage"]: row["facts"] for row in receipt["coverage"]},
                "files": inventories[0],
                "rights": "not_evaluated",
                "observation_scope": "retained_census_not_capture_time_attestation",
            },
            sort_keys=True,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
